project:
  type: book
  output-dir: docs

book:
  title: "Statistical analysis and presentation using R"
  subtitle: "An overview of R functions used in Statistics II"
  author: ["Leila Demarest", "Joshua Robison"]
  date: "2024-08-15"
  chapters:
    - index.qmd
    - part: part_linear.qmd
      chapters: 
      - linear_01.qmd
      - linear_02.qmd
      - linear_03.qmd
      - linear_04.qmd
      - linear_05.qmd
      - linear_06.qmd
      - linear_07.qmd
      - linear_08.qmd
    - part: part_logistic.qmd
      chapters:
      - logit_01.qmd
      - logit_02.qmd
      - logit_03.qmd
      - logit_04.qmd
      - logit_05.qmd
      - logit_06.qmd
    - part: part_interactions.qmd
      chapters: 
      - interaction_01.qmd
      - interaction_02.qmd
      - interaction_03.qmd
  appendices:
    - common_errors.qmd
    - package_overview.qmd
    - Formulas.qmd
    
bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: darkly

editor: visual

